server:
  port: ${SERVER_PORT:8888}
enAble: enAble
a:
  name: zzh
  price: 100
  enable: true
  unkonwn: unKonwn
  duration: 2h
  dataSize: 5MB
  list:
    - 1
    - 2
  map:
    mKey1: mValue1
    mKey2: mValue2
Good:
  name: zzh
  price: 100
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 243167ooOL
    username: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:xml/*.xml
#  全局配置逻辑删除字段
#  global-config:
#    db-config:
#      logic-not-delete-value: 0
#      logic-delete-value: 1
  #打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl